### ISSUE TITLE
What's the jetbrains issue for this?

### ISSUE THREAD

**Issue by cjw296** [micahhausler/pycharm-coverage#1]
Hello,

I'd like to vote for this in the JetBrains tracker, what's the issue url?

Also, did you find a way to get "pragma: no cover" to be respect by PyCharm?

cheers,

Chris

**Comment by micahhausler** [comment]
@cjw296 https://youtrack.jetbrains.com/issue/PY-8698

I'm pretty sure the "pragma: no cover" was respected by my `.coveragerc`
